name: Build Vue
on: [push]
jobs:
  build_vue:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    name: Build Vue
    steps:
    - uses: actions/checkout@v2
    - id: Build-Vue
      uses: xRealNeon/VuePagesAction@1.0.1
      with:
        username: 'knpoblete'
        reponame: 'knpoblete.github.io'
        token: ${{ secrets.GITHUB_TOKEN }} # Leave this line unchanged
        useyarn: true
        env:
        VUE_APP_EMAILJS_SERVICE: ${{ secrets.VUE_APP_EMAILJS_SERVICE }}
        VUE_APP_EMAILJS_TEMPLATE: ${{ secrets.VUE_APP_EMAILJS_TEMPLATE }}
        VUE_APP_EMAILJS_KEY: ${{ secrets.VUE_APP_EMAILJS_KEY }}
